### ISSUE TITLE
Bug When Turning Everything Off

### ISSUE THREAD

**Issue by mrobgithub** [imnotbob/vacation-lighting-director#1]
I ran into a bug when VLD attempts to cycle everything off after completing a session if the user doesn't define any lights to be on during active times. I made a simple code change to wrap the on_during_active_lights.off() call in an if statement to check for null. Seems to work fine now if  the user doesn't define any lights to be on during active times. FYI, I did NOT test the use case where a user defines active lights to be on but it should work fine.

My changes below...

```
def clearState(turnOff = false) {
	if(turnOff && atomicState?.Running) {
		switches.off()
		atomicState.vacactive_switches = []
		if (on_during_active_lights != null) {
			on_during_active_lights.off()
		}
		log.trace "All OFF"
	}
	atomicState.Running = false
	atomicState.schedRunning = false
	atomicState.startendRunning = false
	atomicState.lastUpdDt = null
	unschedule()
}
```

**Comment by imnotbob** [comment]
thx, updated the version with this fix (plus another location)

**Comment by mrobgithub** [comment]
Great! I looked and I had also fixed the second location. It had been a while and I forgot about it so I didn't include it in the ticket. Glad you found it as well.
