### ISSUE TITLE
Unable to add Vacation Lighting Director to SmartThings Classic (Android)

### ISSUE THREAD

**Issue by dhedges01** [imnotbob/vacation-lighting-director#3]
I just loaded the Vacation Lighting Director via the SmartThings IDE and went to set it up in the SmartThings Classic app.  Was able to go thru Setup & Settings and even rename it but there is no Save button.  Only Remove.  So I can't actually add the app itself because there isn't a way to save my changes.

**Comment by imnotbob** [comment]
Save or Done should be in the upper right on the screen in the classic app

**Comment by dhedges01** [comment]
![screenshot_20180802-110436_smartthings](https://user-images.githubusercontent.com/5664465/43596149-129508cc-9644-11e8-8986-360f4b537596.jpg)
Hopefully this screenshot comes thru.

**Comment by imnotbob** [comment]
What client are you using?

On the blue title, there should be a Save next to where you have "Dire..."

I assume you are using the version from the repo.  You might contact ST support, as this is in ST vs. VLD.

**Comment by dhedges01** [comment]
Was able to get the save button to show up. Had to fully reboot the phone. Odd.
